### PR TITLE
Fix crash with WebKit on iOS 9.x.

### LINKED ISSUE #150: [WKWebview] iOS 9 - Crash on unmounting
it works perfectly with ios 10.x.x and greater, but in ios 9.1, it makes app crash when Webview unmount

### PR DESCRIPTION
**Pull request by jerolimov**
This PR fixes two crashes when enableWebKit is true (which was the default) on iOS 9.x. The first one when the WebView component was mounted (fixes issue #150) and the second one, when the component was unmounted (fixes issue #213).

The first problem happen when the RNCWKWebView.m was loaded:

The programming guide for WebKit (version 2006) ([pdf](http://mirror.informatimago.com/next/developer.apple.com/documentation/Cocoa/Conceptual/DisplayWebContent/WebKit_DisplayWebContent.pdf)) from Apple said, that it is (was) required to check if the 'new' WebKit Framework was available. This was required when the WebKit framework was only available on Mac OS X (10.2) when the Safari was installed. 😆

Because WebKit is (currently..) a fix part of iOS we didn't need this check this anymore to determinate if WebKit is available. I also see no other reference that this is required in iOS so I just remove this code. Without this code the WebView works also on iOS 9.x.

The second issue happen when the WKWebView was removed from the native view hierarchy. Its required (only on iOS 9) to remove the UIScrollView delegate before cleaning up the webview.

Its possible to try this PR with:

```
npm install --save "react-native-webview@jerolimov/react-native-webview#fix-ios9-crash"
# or
yarn add "react-native-webview@jerolimov/react-native-webview#fix-ios9-crash"
```

If you use CocoaPods, you should also update your Pods with

```
cd ios && pod update && cd ..
```

### CODE REVIEW

**Comment by jerolimov** [comment]
Its possible to try this PR with:

```
npm install --save "react-native-webview@jerolimov/react-native-webview#fix-ios-crash"
# or
yarn add "react-native-webview@jerolimov/react-native-webview#fix-ios-crash"
```

If you use CocoaPods, you should also update your Pods with

```
cd ios && pod update && cd ..
```

**Comment by Titozzz** [comment]
Cc @adrienharnay

**Comment by Titozzz** [comment]
Great work. Will merge tomorrow after testing 💯

File: ios/RNCWKWebView.m [hunk 1]
```diff
@@ -91,6 +71,11 @@ - (instancetype)initWithFrame:(CGRect)frame
   return self;
 }
 
+- (void)dealloc
+{
+  [[NSNotificationCenter defaultCenter] removeObserver:self];
```
Comment (Titozzz) [inline ios/RNCWKWebView.m]: What does this change do?

Comment (Titozzz) [reply ios/RNCWKWebView.m]: Considering this: https://useyourloaf.com/blog/unregistering-nsnotificationcenter-observers-in-ios-9/

**Comment by AndrewJack** [comment]
Just testing this now, thanks. One thing, there's a typo in your install instructions:
```diff
-yarn add "react-native-webview@jerolimov/react-native-webview#fix-ios-crash"
+yarn add "react-native-webview@jerolimov/react-native-webview#fix-ios9-crash"
```

**Comment by AndrewJack** [comment]
Seems to work. 
Tested before with crash, and after no crash. On an iOS 9.3 Simulator.
👍

**Comment by Titozzz** [comment]
Yeah, I'm just not sure the `[[NSNotificationCenter defaultCenter] removeObserver:self]` is mandatory, but everything else is good. I'll merge when @jerolimov replies to the comment above.

**Comment by AndrewJack** [comment]
Not sure about that line either. Doesn't look like it's needed 🤷‍♂️.

**Comment by jerolimov** [comment]
@AndrewJack Could catch 😄  Thanks for verifying this.

File: ios/RNCWKWebView.m (hunk 1 above)
Comment (jerolimov) [reply ios/RNCWKWebView.m]: Oh maybe this isn't required, but the init method ~10 lines above registers the RNCWKWebView class as observer. So I think its "good style" remove the observer (or any other listener, subscriptions) when the class was deallocated. I could remove the dealloc method if you think this could confuse someone. I would prefer to keep it.
